name: Deploy To Prod S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: AWS 인증 절차
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 의존성 설치
        run: |
          cd main_project
          npm install

      - name: React 프로젝트 빌드
        run: |
          cd main_project
          npm run build

      - name: S3 기존 파일들 삭제 후 새로 업로드
        run: |
          aws s3 rm --recursive s3://prod-feelody-web
          aws s3 cp ./main_project/dist s3://prod-feelody-web --recursive

      - name: cloudfront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E26D48U2H6Q45B --paths "/*"
